name: Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        
      - name: Check out code
        uses: actions/checkout@v2

      - name: Tidy Go module
        run: go mod tidy

      - name: PREFormat Terraform 
        run: |
        
         go run main.go
        
